Reference
---------

1. [joyfulpandas](https://datawhalechina.github.io/joyful-pandas/build/html/%E7%9B%AE%E5%BD%95/ch1.html#id3)
2. [numpy 中文网](https://www.numpy.org.cn/)

练习
------

1. 利用列表推导式写矩阵乘法
```python
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = [[sum([M1[i][k] * M2[k][j] for k in range(M1.shape[1])]) for j in range(M2.shape[1])] for i in range(M1.shape[0])]
```


2. 更新矩阵
```python
A = np.arange(1,10).reshape(3,-1)
B = A*(1/A).sum(1).reshape(-1,1)
```


3. 卡方统计量
```python
np.random.seed(0)
A = np.random.randint(10, 20, (8, 5))
B = A.sum(0)*A.sum(1).reshape(-1, 1)/A.sum()
res = ((A-B)**2/B).sum()
```


4. 改进矩阵计算的性能
```python
def solution(B=B, U=U, Z=Z):
    L_res = []
    for i in range(m):
     for j in range(n):
         norm_value = ((B[i]-U[:,j])**2).sum()
         L_res.append(norm_value*Z[i][j])
    return sum(L_res)
```


5. 连续整数的最大长度
```python
f = lambda x:np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1])).max()
f([1,2,5,6,7])
```

# 1. 数组构造

In [1]:
import numpy as np

普通

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

等差序列   
`np.linespace`, `np.arange`

In [3]:
np.linspace(1, 5, 11)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [4]:
np.arange(1, 5, 2)

array([1, 3])

特殊矩阵   
`zeros`, `eye`, `full`

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# 部分参数释义

# M : int, optional
#   Number of columns in the output. If None, defaults to `N`.
# k : int, optional
#   Index of the diagonal: 0 (the default) refers to the main diagonal,
#   a positive value refers to an upper diagonal, and a negative value
#   to a lower diagonal.

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
# 参数 fill_value
# 为列表时，会被作为每列的值填充

np.full((2, 3), fill_value=10)

array([[10, 10, 10],
       [10, 10, 10]])

随机矩阵   
`np.random`    
    
    - rand 0-1 均匀分布
    - randn 标准正太的随机数组
    - randint 随机整数数组
    - choice 随机列表抽样
    - seed 固定随机数的输出效果

In [8]:
# 0-1 均匀分布
# 参数释义

# d0, d1, ..., dn : int, optional
#     The dimensions of the returned array, should all be positive.
#     If no argument is given a single Python float is returned.

np.random.rand(3)

array([0.82187773, 0.15285284, 0.86876682])

生成服从取间 `a` 到 `b` 上的均匀分布

In [9]:
a, b = 5, 15
(b - a) * np.random.rand(3) + a

array([10.72063424, 13.13639831, 12.98014531])

In [10]:
np.random.choice('a b c d'.split(), 2, replace=False, p=[0.1, 0.7, 0.1, 0.1])

array(['d', 'b'], dtype='<U1')

In [11]:
np.random.choice('a b c d'.split(), 4)

array(['b', 'a', 'a', 'c'], dtype='<U1')

In [12]:
np.random.permutation('a b c d'.split())  # 打散

array(['c', 'b', 'a', 'd'], dtype='<U1')

# 2. 数组变形与合并

In [13]:
arr = np.zeros((2, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
arr.T  # 转置

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.r_[arr, arr]  # 上下合并

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.c_[arr, arr]  # 左右合并

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr.reshape(3, 2)  # 维度变换

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
arr.reshape(-1)

array([0., 0., 0., 0., 0., 0.])

In [19]:
arr.reshape((6, -1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

# 3. 数组切片与索引

In [20]:
arr3 = np.arange(9).reshape(3, 3)

In [21]:
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
arr3[:-1]  #  start:end:step 

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
arr3[[0, 2]]  # 指定维度

array([[0, 1, 2],
       [6, 7, 8]])

In [24]:
arr3[np.ix_([True, False, True])]

array([[0, 1, 2],
       [6, 7, 8]])

# 4. 常用函数

1. `where`       指定满足条件与不满足条件位置对应的填充值
2. `nonzero`     返回非零数的索引


3. `argmax`      返回最大数索引
4. `argmin`      返回最小数索引


5. `any` & `all` 效果同内置同名函数   


6. `cumprod`     累乘 返回数组
7. `cumsum`      累加 返回数组
8. `diff`        和前一个元素做差，返回数组（长度为原数组减 1）


9. `max` & `min` & `mean` ...
10. `std` ...
11. `var` ...
12. `sum`
13. `np.median` 中位数
14. `np.quantile` 分位数

In [25]:
arr4 = np.array([-1, 1, -1, 0])

In [26]:
np.where(arr4 > 0, arr4, 5)

array([5, 1, 5, 5])

# 5. 广播机制

# 6. 向量与矩阵的计算

1. `dot`  向量内积
2. `np.linalg.norm`  向量范数和矩阵范数
3. `@`  矩阵乘法